### ISSUE TITLE
Softness should be float greater zero

### ISSUE THREAD

**Issue by ppyt** [flxai/soft-brownian-offset#1]
ValueError: Softness should be float greater zero
Please help check this bug,thanks

**Comment by flxai** [comment]
Can you please post the Python code that leads to this error, @ppyt?

**Comment by ppyt** [comment]
I just run the eaxmple code and got that bug.

**Comment by ppyt** [comment]
> Can you please post the Python code that leads to this error, @ppyt?



> Can you please post the Python code that leads to this error, @ppyt?
I just run the eaxmple code and got that bug.

**Comment by flxai** [comment]
Thanks for pointing it out, @ppyt.

I adapted the code to match the documentation. The old version expected `softness` to be `False`, but you now can use `softness=0` as it is shown in the documentation. Does it work for you now? Try to update your version of the library using e.g.:

```
$ pip install --upgrade sbo
```

Does this work for you?
